name: Update README

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme for RSS Reader
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install rss-parser
      - name: Fetch RSS feed and update README
        run: node .github/scripts/update-readme.js
