name: Update README

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-readme:
    name: Update Readme for RSS Reader
    runs-on: ubuntu-latest
    steps:
      # it is crucial in my git Actions workflow becuase it checks out  the repository under $GITHUB_WORKSPACE.
      # It allows your workflow to access it.
      - name: Checkout
      - uses: actions/checkout@v3
      # sets up a Node.js environment and configures.
      - name: nodejs_environment
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install rss-parser
      - name: Fetch RSS feed and update README
        run: node .github/scripts/update-readme.js
